### ISSUE TITLE
Remove output color profile from darkroom

### ISSUE THREAD

**Issue by aurelienpierre** [Aurelien-Pierre/R-Darktable#25]
The output color profile module in darkroom has a color space parameter that can be set by the user. However, this will get overridden by :

* the display profile, for previews and thumbnails,
* the export profile, for exports.

There is a slightly deviant way of using it, though, by using the "image setting" option in the export box "profile" setting. But this is mostly unused, since there is no way to know what this image setting actually is at export time, and it is impractical to check it for batch export.

That is to say that the in-module profile is at best useless, and at worst misleading to less experienced users.

Solution:

* remove the color output profile from darkroom's GUI,
* rename the "image settings" option of the export box "same as original",
* make the "same as original" option use the embedded profile of the original image if any, else default to sRGB. This will be useful for example to resize or crop a batch of images using different color spaces without rewriting their color space.

Check list:

- [ ] : RAWs (non-DNG) exported with "same as original" should export as sRGB
- [ ] : DNG with embedded matrix exported with "same as original" should export with their original matrix (in linear RGB, expect posterization in shadows if using 8 bits) and have it embedded,
- [ ] : JPEG / PNG / TIFF exported with "same as original" should use the same color space as the original space.
- [ ] : RAWs exported with any color space should work as previously.

How to check color profiles:

1. open the pictures in Gimp or Krita, output should look the same,
2. Using `exiv2 -g ColorSpace test.jpg`, should return:
```shell
Exif.Photo.ColorSpace                        Short       1  sRGB
```
for sRGB exports, or for any other space:
```shell
Exif.Photo.ColorSpace                        Short       1  Uncalibrated
```
3. Using `exiftool -icc_profile:* test.jpg` should return various useful info, like the color space name:
```bash
Device Model Desc               : Adobe RGB
Device Mfg Desc                 : darktable
```
or the color matrix of the color space embedded in the file:
```bash
Profile Description             : Adobe RGB (compatible)
Profile Copyright               : Public Domain
Media White Point               : 0.9642 1 0.82491
Chromatic Adaptation            : 1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
Red Matrix Column               : 0.60974 0.31111 0.01947
Blue Matrix Column              : 0.14919 0.06322 0.74455
Green Matrix Column             : 0.20528 0.62567 0.06087
```
you can compare it with the color matrix of your original file if any.

**Comment by jorismak** [comment]
'same as original' sounds weird in case of RAW files, isn't it?

I know of a lot of people who think their raw files are different when setting the camera to 'sRGB' or 'AdobeRGB'. It's hard to explain that only effects to preview-jpeg, not the RAW file sometimes...

So, what does 'same as original' do when loading a raw file? Seems undefined?

Another remark along the same lines: 'Same as original' for RGB images might give the impression that there is no conversion done from input to output, while - if I remember the pipeline correctly - DT will convert to the working profile (linear rec2020 by default) and then convert back to the output one.

Third one, which is more of a question to you: With all the gamut mapping, is there a module or a point which reads the output profile to use in gamut-mapping / hue preserving / some other stuff I don't understand ?
And if it's removed from the output module, does that effect it somehow? Or does the 'export profile' setting now suddenly affect the output of modules like filmic?

(In a way it makes sense, that way you can render one to sRGB, one to AdobeRGB, one to Rec2020 for instance, all the while using the maximum gamut the output profile has to offer...  But on the other hand, it kinda makes it hard to know what the output is going to look like before actually exporting?).

**Comment by aurelienpierre** [comment]
> 'same as original' sounds weird in case of RAW files, isn't it?

As written above, it will default to sRGB for raw files. The general problem is exporting in batch can select different kinds of files, so the "same as original" will have to adapt to the input data.

> Another remark along the same lines: 'Same as original' for RGB images might give the impression that there is no conversion done from input to output, while - if I remember the pipeline correctly - DT will convert to the working profile (linear rec2020 by default) and then convert back to the output one.

Yes but. The conversion to Rec 2020 is done without gamut mapping and RGB values are left unclipped, so if no color module is applied in-between (for example, the pipeline only crops the image), the color conversion is non-destructive no matter if the in & out color spaces are larger than Rec 2020.

> Third one, which is more of a question to you: With all the gamut mapping, is there a module or a point which reads the output profile to use in gamut-mapping / hue preserving / some other stuff I don't understand ?
And if it's removed from the output module, does that effect it somehow? Or does the 'export profile' setting now suddenly affect the output of modules like filmic?

Filmic v6 is the only bit that reads the output profile and check if each RGB pixel will lie within the output color space gamut. If not, chroma is clipped at constant hue and luminance as to fit within gamut. Color balance RGB checks if its output RGB fits within the working color space, typically Rec 2020. 

In any case, the output color profile module never did gamut mapping, other than clipping RGB to [0; 1]. Note that **it is not removed from the pipeline**, it is only hidden from the darkroom GUI since the output color space is defined in the display options or in the export options.

**Comment by aurelienpierre** [comment]
Merged.
